<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <style>
        body { font-family: Arial, sans-serif; font-size: 14px; color: #374151; }
        .header { background: #1d4ed8; color: #fff; padding: 20px 30px; }
        .content { padding: 30px; }
        .footer { padding: 20px 30px; border-top: 1px solid #e5e7eb; color: #6b7280; font-size: 12px; }
    </style>
</head>
<body>
    <div class="header">
        <h2 style="margin:0;">Star Yamaha — Salesman Register Report</h2>
    </div>
    <div class="content">
        <p>Please find attached the Salesman Register Report for the period:</p>
        <p style="font-size:16px; font-weight:bold;">
            {{ $startDate->format('d/m/Y') }} to {{ $endDate->format('d/m/Y') }}
        </p>
        <p>The report is attached as a {{ $format }} file.</p>
    </div>
    <div class="footer">
        <p>Generated by Star Yamaha DMS</p>
    </div>
</body>
</html>
